language: java
sudo: false
script: mvn clean verify

# SonarCloud
dist: trusty
addons:
  sonarcloud:
    organization: "chaudhryhaseeb-github" # the key of the org you chose at step #3
    token:
      secure: 5a72427776432a9a6be1198b0b08e2cb855e3c1b # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar